### ISSUE TITLE
support gateway detection

### ISSUE THREAD

**Issue by aparcar** [aparcar/meshrc#2]
prometheus-node-exporter-lua-bmx7 should detect if a node works as a gateway.

@axn is there a way to check if a node announces 0.0.0.0/0?

**Comment by axn** [comment]
On 02.04.2018 08:12, Paul Spooren wrote:
> prometheus-node-exporter-lua-bmx7 should detect if a node works as a
> gateway.
> 
> @axn <https://github.com/axn> is there a way to check if a node
> announces 0.0.0.0/0?


Which nodes announce something with /0 can be seen with bmx7 -c tunnels
via the advNet column.

Or via json by parsing /var/run/bmx7/descriptions/*

Look for something like:
      "DSC_TUN4IN6_NET": [
        {
          "tun6Id": 0,
          "rtype": 0,
          "bandwidth": "257G",
          "networkLen": 0,
          "network": "0.0.0.0"
        }
      ]
    },
    {
      "DSC_TUN6IN6_NET": [
        {
          "tun6Id": 0,
          "rtype": 0,
          "bandwidth": "257G",
          "networkLen": 0,
          "network": "::"
        }
      ]
    },

**Comment by aparcar** [comment]
fixed via https://github.com/aparcar/meshrc/commit/ca149ffaa65a00b7cef3871cde548b8bfcb5beb0
