### ISSUE TITLE
multiple server nodes

### ISSUE THREAD

**Issue by tomjones1977** [aparcar/meshrc#5]
Is it possible to run multiple servers?  I have a mesh that may split and cannot guarantee that the server node will always be connected but don't want to lose the mapping functionality of meshrc.

**Comment by aparcar** [comment]
hey @tomjones1977 , thanks for you interest. Per design every participant of the network can be a *server*, meaning a device that collect and aggregates stats. Just install a second `meshrc-web` on whatever node you think will be in the *other part of the mesh network*.

To control nodes, you can set multiple nodes as *trusted*.
